Repository OIRNOIR/WackyWebM, pull requests merged in 2022-08, with the labels that each got.

#9 Added shrink option
  README.md
  wackywebm.js
Labels: enhancement

#17 Add ESLint and Prettier for formatting and style consistency
  .eslintrc.json
  .gitignore
  .prettierrc.json
  README.md
  package-lock.json
  package.json
  wackywebm.js
Labels: enhancement

#35 Automation scripts
  .github/format.js
  .github/workflows/update-scripts.yml
  wackywebm.js
Labels: enhancement

#31 Audio-Both mode + first frame is original size so video is still playable
  run.bat
  run.sh
  wackywebm.js
Labels: enhancement, modes

#25 Added 'jumpscare' mode
  wackywebm.js
Labels: enhancement, modes

#44 Small fix for Run Scripts!
  run.bat
  run.sh
Labels: bug

#45 Fix github actions
  .github/workflows/update-scripts.yml
Labels: bug

#38 fix jumpscare lol
  modes/jumpscare.js
Labels: bug

#41 only create new webm file if size actually changed
  README.md
  wackywebm.js
Labels: enhancement

#53 README.md
  README.md
Labels: documentation

#46 Optimize command parsing
  modes/rotate.js
  util.js
  wackywebm.js
Labels: bug, enhancement

#58 minor improvements + COMPRESSION (again again)
  README.md
  modes/jumpscare.js
  modes/keyframes.js
  modes/rotate.js
  util.js
  wackywebm.js
Labels: bug

#64 Fix compression and command parse
  modes/jumpscare.js
  wackywebm.js
Labels: bug

#62 terminal UI
  .github/format.js
  .github/workflows/update-scripts.yml
  package-lock.json
  package.json
  run.bat
  run.sh
  terminal-ui.js
  wackywebm.js
Labels: enhancement

#86 Switch localization to json files
  localisation.js
  localisations/english.js
  localization.js
  localizations/en_us.json
  modes/keyframes.js
  terminal-ui.js
  util.js
  wackywebm.js
Labels: enhancement

#88 minor kf fixes; "instant" interpolation mode
  README.md
  localizations/en_us.json
  modes/keyframes.js
Labels: enhancement, modes

#102 fix localization
  localization.js
Labels: bug
